-record(dstree,
        {id,
         status = initial,
         origin,
         parent,
         neighbors = ordsets:new(),
         children = ordsets:new(),
         subtree = orddict:new(),
         tree,
         dbg_fun,
         report_fun,
         send_fun = fun dstree:default_send/2}).
