-record(dstree,
        {id,
         status = initial,
         origin,
         depth = 0,
         parent,
         children = ordsets:new(),
         neighbors = ordsets:new(),
         subtree = orddict:new(),
         dead = ordsets:new(),
         tree,
         waiting_timeout,
         waiting_for,
         timers = orddict:new(),
         dbg_fun,
         report_fun,
         send_fun = fun dstree:default_send/2}).
